title: "Async Channels"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: false
permalink: pretty

back_to_top: true
back_to_top_text: "Back to top"

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

footer_content: "Distributed by a <a href=\"https://github.com/Eyal-Shalev/async_channels/tree/master/LICENSE.txt\">GPL 3+ Licence</a>."

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all
