title: "Async Channels"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: false
permalink: pretty

aux_links_new_tab: true

back_to_top: true
back_to_top_text: "Back to top"

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

footer_content: "Distributed by a <a href=\"https://github.com/Eyal-Shalev/async_channels/tree/master/LICENSE.txt\">GPL 3+ License</a>."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

compress_html:
  ignore:
    envs: all
