title: "Async Channels"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: false
permalink: pretty
baseurl: "/async_channels"
url: "https://eyal-shalev.github.io"

aux_links_new_tab: true

back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  "Async Channels on GitHub": "//github.com/Eyal-Shalev/async_channels"
  "API": "//doc.deno.land/https/deno.land/x/async_channels/mod.ts"

search_enabled: true

compress_html:
  ignore:
    envs: all
