name: Pre Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: bash ./scripts/run-tests.bash

  bundle:
    runs-on: "ubuntu-latest"
    needs: test

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Deno bundle
        run: bash ./scripts/bundle.bash

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  rollup:
    runs-on: "ubuntu-latest"
    needs: bundle
    env:
      FORMATS: |
        amd
        cjs
        iife
        umd
        system
    
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Setup Rollup
        run: npm install --global rollup rollup-plugin-terser

      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Create Bundles
        run: |
          for f in $FORMATS; do rollup dist/esm.bundle.js --file dist/"$f".bundle.js --format "$f" --name asyncChannel; done
          for f in $FORMATS; do rollup dist/esm.bundle.js --file dist/"$f".bundle.min.js --format "$f" --name asyncChannel --plugin terser; done

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  pre-release:
    name: "Pre Release"
    runs-on: ubuntu-latest
    needs: rollup
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: true
          automatic_release_tag: latest
          files: |
            LICENSE
            README.md
            dist/*.bundle.js
            dist/*.bundle.min.js
