name: Test

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main]
    tags:
      - v*

env:
  BUNDLE_NAME: async_channels

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: make fmt-check

      - name: Run linter
        run: make lint

      - name: Run tests (with coverage)
        run: make coverage

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          fail_ci_if_error: true
          verbose: true

  build-npm:
    name: Test NPM build
    if: ${{ always() }}
    strategy:
      matrix:
        registry: [npmjs, github]
        include:
          - registry: npmjs
            scope: "eyalsh"
            registry-url: https://registry.npmjs.org
          - registry: github
            scope: "Eyal-Shalev"
            registry-url: 'https://npm.pkg.github.com'
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - uses: ./.github/build-npm
        with:
          scope: ${{ matrix.scope }}
          registry-url: ${{ matrix.registry-url }}
          dist: dist-${{ matrix.registry }}

  build-iife:
    name: Test IIFE build
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - uses: ./.github/build-iife
