name: Test & Release

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    tags:
      - v*

env:
  BUNDLE_NAME: async_channels

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: make fmt-check

      - name: Run linter
        run: make lint

      - name: Run tests (with coverage)
        run: make coverage

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          fail_ci_if_error: true
          verbose: true

  version:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Get version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\/v/}
      - name: Is pre-release
        id: is_pre
        run: echo ::set-output name=IS_PRE::"$([[ $GITHUB_REF =~ refs\/tags\/v.+-.+ ]] && echo 0 || echo 1)"
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      is_pre: ${{ steps.is_pre.outputs.IS_PRE }}

  build-npm:
    needs: [version]
    if: ${{ always() }}
    strategy:
      matrix:
        registry: [npmjs, github]
        include:
          - registry: npmjs
            scope: "eyalsh"
            registry-url: https://registry.npmjs.org
          - registry: github
            scope: "Eyal-Shalev"
            registry-url: 'https://npm.pkg.github.com'
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: ${{ matrix.registry-url }}

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install
        run: make install

      - name: Build
        run: make build-npm
        env:
          VERSION: ${{ needs.version.outputs.version || '0.0.0-test' }}
          SCOPE: ${{ matrix.scope }}

      - uses: actions/upload-artifact@v2
        with:
          name: dist-${{ matrix.registry }}
          path: dist

  publish:
    name: Publish
    needs: [test, build-npm, version]
    strategy:
      matrix:
        registry: [npmjs, github]
        include:
          - registry: npmjs
            registry-url: https://registry.npmjs.org
          - registry: github
            registry-url: 'https://npm.pkg.github.com'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: dist-${{ matrix.registry }}
          path: dist

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: ${{ matrix.registry-url }}

      - run: npm publish
        name: publish - npmjs
        if: ${{ matrix.registry == 'npmjs' }}
        working-directory: dist/npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npm publish
        name: publish - github
        if: ${{ matrix.registry == 'github' }}
        working-directory: dist/npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-iife:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install
        run: make install

      - name: Build
        run: make build-iife

      - uses: actions/upload-artifact@v2
        with:
          name: dist-iife
          path: dist

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [test, build-iife, version]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: dist-iife
          path: dist

      - uses: marvinpinto/action-automatic-releases@latest
        if: ${{ needs.version.outputs.is_pre }}
        with:
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: Version ${{ needs.version.outputs.version }}
          automatic_release_tag: ${{ needs.version.outputs.version }}
          files: |
            LICENSE
            README.md
            dist/async_channels.iife.js
            dist/async_channels.iife.min.js

      - uses: marvinpinto/action-automatic-releases@latest
        if: ${{ ! needs.version.outputs.is_pre }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: Version ${{ needs.version.outputs.version }}
          automatic_release_tag: ${{ needs.version.outputs.version }}
          files: |
            LICENSE
            README.md
            dist/async_channels.iife.js
            dist/async_channels.iife.min.js
