name: Test

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main]
    tags:
      - v*

env:
  BUNDLE_NAME: async_channels

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: make fmt-check

      - name: Run linter
        run: make lint

      - name: Run tests (with coverage)
        run: make coverage

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          fail_ci_if_error: true
          verbose: true

  build-npm:
    name: Test NPM build
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - uses: ./.github/build-npm
        with:
          scope: test
          version: 0.0.0-${{GITHUB_SHA}}

  build-iife:
    name: Test IIFE build
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - uses: ./.github/build-iife
